sighupio/distribution

.drone.yml, .rules/.markdown-lint.yml, DEVELOPMENT.md, Furyfile.yml, README.md, docs/releases/v1.3.0.md, katalog/tests/dr.sh, katalog/tests/ingress.sh, katalog/tests/install.sh, katalog/tests/logging.sh, katalog/tests/monitoring.sh, katalog/tests/networking.sh, katalog/tests/opa.sh, release-notes.py
This PR aims to release Fury v1.3.0 adding support to Kubernetes 1.16, 1.17 and 1.18.
Is not a big release in terms of features, but is a step forward to have an updated supported distribution (and certified).
I will work on pending stuff after merging the pr (technical release).
We can promote the new version once:
- docs site is updated
- CNCF verifies our distribution
- having a blog post
Thanks!
=> Release 1.3.0

.drone.yml, Furyfile.yml, README.md, docs/releases/v1.6.0.md
Welcome to the **Fury Distribution v1.6.0**. In this new version, we had addressed the update of multiples
packages that belong to the distribution. All of them have been pushed to the latest stable release of each.
It includes testing (as tech preview) against Kubernetes `v1.21.0`.
The team has been working to make the release upgrade as simple as possible, so read carefully the upgrade path of each
core module listed below along with the upgrade path of the distribution.
The most important changes are listed below:
- [networking](https://github.com/sighupio/fury-kubernetes-networking) 📦 core module: v1.5.0 -> [**v1.6.0**](https://github.com/sighupio/fury-kubernetes-networking/releases/tag/v1.6.0)
- Kubernetes `1.21` Tech preview.
- Update [Calico] from version `3.17.1` to `3.19.1`.
- …
=> Fury Distribution v1.6.0

.drone.yml, Furyfile.yml, docs/releases/v1.7.0.md, kustomization.yaml, release-notes.py
This PR release a RC for fury-distribution 1.7.0. This release adds the tech preview for Kuberenetes 1.22. Refer [release notes](https://github.com/sighupio/fury-distribution/blob/43c840404d619203bc540520459618b9d95babad/docs/releases/v1.7.0.md) to see other changes.
=> Prepare fury-distribution pre-release 1.7.0-rc

source/terraform/velero.tf.tpl
=> fix: removing '-velero' suffix on terraform templates

kfd.yaml
bump AWS module version to add support for Kubernetes 1.24
=> chore(kfd.yaml): bump aws module version

templates/config/ekscluster-kfd-v1alpha2.yaml.tpl, templates/distribution/_helpers.tpl, templates/distribution/manifests/auth/patches/pomerium-ingress.yml.tpl, templates/distribution/manifests/auth/resources/ingress-infra.yml.tpl, templates/distribution/manifests/auth/resources/pomerium-config.env.tpl, templates/distribution/manifests/auth/resources/pomerium-policy.yml.tpl, templates/distribution/manifests/auth/secrets/dex.yml.tpl, templates/distribution/manifests/ingress/kustomization.yaml.tpl, templates/distribution/manifests/ingress/resources/ingress-infra.yml.tpl, templates/distribution/manifests/logging/resources/ingress-infra.yml.tpl, templates/distribution/manifests/monitoring/resources/ingress-infra.yml.tpl, templates/distribution/manifests/opa/resources/ingress-infra.yml.tpl
This pr addresses #42 and #41 
The notable changes are : 
- now pomerium is ingressClass external in the case of dual ingresses
- all the other ingresses are create in the pomerium namespace if auth is sso, and the target service is always pomerium
- the policy field under pomerium configuration, is only "additional" from the infra ingresses
- a new `baseDomain` field is added to the auth module, to manage the SSO auth urls in a different way from the other ingresses
This PR needs to be reviewed after #38
=> Feat: improve and fix sso on distro template

kfd.yaml, templates/config/ekscluster-kfd-v1alpha2.yaml.tpl, templates/distribution/manifests/auth/secrets/basic-auth.yml.tpl, templates/distribution/terraform/cert-manager.tf.tpl, templates/distribution/terraform/external-dns.tf.tpl
Plus commenting out optional fields in the template.
TODO: Release a new ingress module version with the aws-cert-manager module fixed to work with furyctl ng
=> [Furyctl next] template terraform distro for ext dns

kfd.yaml, pkg/schema/ekscluster_kfd_v1alpha2.go, schemas/ekscluster-kfd-v1alpha2.json, templates/config/ekscluster-kfd-v1alpha2.yaml.tpl
Changelist:
- improved comment on additionalFirewallrules.cidrBlocks about current support to only one rule
- improved schema, now cidrBlocks needs to have at least one element
=> chore: added comment to cidr_blocks to only support 1 at the moment

templates/config/ekscluster-kfd-v1alpha2.yaml.tpl
comment out the spec.distribution.modules.ingress.nginx.tls.secret section in the sample configuration file for EKSCluster because the default in the sample is using cert-manager instead of a custom certificate.
fixes #53
=> Fix: comment secret section in sample configuration

docs/releases/v1.25.0.md
Auth module was introduced in KFD 1.24.0
notice that I've already edited the release in GitHub with this change
=> docs(release-1.25): remove "new auth module" announcement

docs/upgrades/v1.24.0-to-v1.25.0.md
remove `--force-conflicts` flag from the upgrade guide instructions. This is not needed anymore.
The `--force-conflicts` flag was needed while migrating from client-side apply to server-side.
=> docs: remove force conflicts from v1.24.0-to-v1.25.0.md

templates/distribution/manifests/ingress/patches/ingress-nginx.yml.tpl
We are using the new configuration on dual nginx, but is missing on single flavour, adding it now
=> feat: update single nginx svc to use ALB controller and proxy protocol

pkg/apis/ekscluster/v1alpha2/private/schema.go, pkg/apis/ekscluster/v1alpha2/public/schema.go, schemas/private/ekscluster-kfd-v1alpha2.json, schemas/public/ekscluster-kfd-v1alpha2.json
Changelist:
- added type AwsS3BucketNamePrefix to EKS schema
- now spec.infrastructure.vpn.bucketNamePrefix uses AwsS3BucketNamePrefix
=> Fix: handle "-" and "." in vpn bucketNamePrefix

kfd.yaml, schemas/public/onpremises-kfd-v1alpha2.json, templates/kubernetes/onpremises/hosts.yaml.tpl
enable the usage of the advanced configuration for containerd introduced by https://github.com/sighupio/fury-kubernetes-on-premises/pull/68
=> feature(on-premises): support advanced containerd configuration

rules/ekscluster-kfd-v1alpha2.yaml, rules/kfddistribution-kfd-v1alpha2.yaml, rules/onpremises-kfd-v1alpha2.yaml, templates/distribution/scripts/pre-apply.sh.tpl
When we change the parameter on modules.policy.type from one value to another:
- kyverno to none
- gatekeeper to none
- gatekeeper to kyverno not supported
- kyverno to gatekeeper not supported
=> add policy module migrations when disabled

rules/ekscluster-kfd-v1alpha2.yaml, rules/kfddistribution-kfd-v1alpha2.yaml, rules/onpremises-kfd-v1alpha2.yaml, templates/distribution/scripts/pre-apply.sh.tpl
Handle migrations for changing the installation of default policies in the policy module.
Add migrations for Gatekeeper and Kyverno.
Tested with an on-prem cluster:
- Ran furyctl with Gatekeeper as policy type with the default policies enabled, checked that they were working. Then disabled the default policies, ran furyctl and verified that the Constraints, Constraints Templates and Configs were deleted.
- Disabled Gatekeeper (policy type -> None) ran furyctl, re ran furyctl with Kyverno enabled with the defaults policies set to true. Checked that they were deployed and working. Then disabled the default policies and checked that they were removed from the cluster.
Fixes https://github.com/sighupio/product-management/issues/321
> [!IMPORTANT]
> Depends on …
=> feat: default policies migration

templates/distribution/manifests/opa/kustomization.yaml.tpl
Deploy the monitoring options for Gatekeeper only when the monitoring module is enabled. Otherwise the installation may fail because of missing APIs from Prometheus.
=> feat(templates/policy): install Gatekeeper monitoring if needed

rules/ekscluster-kfd-v1alpha2.yaml, rules/kfddistribution-kfd-v1alpha2.yaml, rules/onpremises-kfd-v1alpha2.yaml, templates/distribution/scripts/pre-apply.sh.tpl, tests/e2e-kfddistribution-5-migrate-from-mimir-to-none.sh, tests/e2e-kfddistribution.sh, tests/e2e/kfddistribution/furyctl-5-migrate-from-mirmir-to-none.yaml
- Add support for changing the monitoring type from prometheus to none and from mimir to none. This will effectively delete the monitoring stack from the cluster.
- Prometheus to Mimir, and Mimir to Prometheus are not supported.
- Add e2e test for Mimir to None.
scenario tested with an on-prem cluster:
- deployed with `montioring.type = prometheus`, verified monitoring stack working.
- changed to `monitoring.type = none`, verified removal of monitoring stack.
- changed to `monitoring.type = mimir`, verified monitoring stack working.
- changed to `monitoring.type = none`, verified removal of monitoring stack.
Fixes https://github.com/sighupio/product-management/issues/324
=> feat(migrations): support monitoring.type to none

templates/kubernetes/onpremises/56.upgrade-worker-nodes.yml.tpl
- added check that all pods are in either `Running` or `Completed` state in upgrade worker nodes playbook
=> feat: upgrade improvements

kfd.yaml, pkg/apis/ekscluster/v1alpha2/private/schema.go, pkg/apis/ekscluster/v1alpha2/public/schema.go, pkg/apis/kfddistribution/v1alpha2/public/schema.go, pkg/apis/onpremises/v1alpha2/public/schema.go, schemas/private/ekscluster-kfd-v1alpha2.json, schemas/public/ekscluster-kfd-v1alpha2.json
This PR introduces a new field `spec.kubernetes.logTypes` in our Kubernetes configuration schema to specify the types of logs that should be collected and managed. This field is defined as an array of strings, allowing for the inclusion of various log types such as `api`, `audit`, `authenticator`, `controllerManager`, and `scheduler`. This enhancement facilitates more granular control over logging preferences and integration with logging tools.
The schema addition is as follows:
```json
"logsTypes": {
"type": "array",
"items": {
"type": "string",
"enum": ["api", "audit", "authenticator", "controllerManager", "scheduler"]
},
"minItems": 0
}
```
To align this new configuration capability with our EKS installation process, a corresponding Terraform variable `cluster_enabled_log_types` has …
=> feat(eks-installer): update schema to add logtypes spec.kubernetes

kfd.yaml, pkg/apis/ekscluster/v1alpha2/private/schema.go, pkg/apis/ekscluster/v1alpha2/public/schema.go, pkg/apis/kfddistribution/v1alpha2/public/schema.go, pkg/apis/onpremises/v1alpha2/public/schema.go, schemas/private/ekscluster-kfd-v1alpha2.json, schemas/public/ekscluster-kfd-v1alpha2.json
This PR makes the following key updates:
- Cherry-picked commit `168973779ee6c4cdd57e8d2c0a3168b789f642b6` to integrate logging capabilities from Kubernetes v1.27.
- Updated the JSON schema to include `spec.kubernetes.logsTypes`, aligning with Kubernetes v1.27 standards.
- Modified the KFD to reference the new EKS installer version 3.1.0, ensuring compatibility with the updated schema.
- Enhanced logging configuration flexibility in release 125 by incorporating these changes.
=> feat(schema): Update JSON schema & EKS installer to v3.1.0 for Kubernetes v1.27 logging

templates/kubernetes/onpremises/create-playbook.yaml.tpl
Use the node pool name defined in the furyctl.yaml as the well-knonw label used to define the "role" by kubectl.
Only for nodes that are not the control-plane because the control-plane role is set by kubeadm.
This will be executed as part of the Kubernetes phase and after the creation of the cluster.
=> feat(on-premises): set nodes roles with the node pool name

templates/distribution/manifests/ingress/patches/infra-nodes.yml.tpl
certmanager is always installed as a dependency of the distribution, so we always apply nodeSelectors and Tolerations to certmanager instead of checking if ingress.tls.type is certmanager.
=> fix(templates/ingress): always apply nodeSelector and Tolerations for certmanager

templates/distribution/manifests/monitoring/patches/infra-nodes.yml.tpl
Add missing nodeSelector and Tolerations to mimir, so it is deployed in the desired nodes like the rest of the infra components.
=> fix(templates/monitoring): add nodeSelectors and Tolerations to mimir

templates/distribution/manifests/auth/resources/pomerium-policy.yml.tpl
Add needed configuration to Pomerium policy so websockets in Grafana and Minio ingresses work.
=> fix(templates/auth): make websockets work with Pomerium

defaults/ekscluster-kfd-v1alpha2.yaml, defaults/kfddistribution-kfd-v1alpha2.yaml, defaults/onpremises-kfd-v1alpha2.yaml, pkg/apis/ekscluster/v1alpha2/private/schema.go, pkg/apis/ekscluster/v1alpha2/public/schema.go, pkg/apis/kfddistribution/v1alpha2/public/schema.go, pkg/apis/onpremises/v1alpha2/public/schema.go, rules/ekscluster-kfd-v1alpha2.yaml, rules/kfddistribution-kfd-v1alpha2.yaml, rules/onpremises-kfd-v1alpha2.yaml, schemas/private/ekscluster-kfd-v1alpha2.json, schemas/public/ekscluster-kfd-v1alpha2.json, schemas/public/kfddistribution-kfd-v1alpha2.json, schemas/public/onpremises-kfd-v1alpha2.json, schemas/public/spec-distribution-custompatches.json, schemas/public/spec-distribution-modules-auth-pomerium.json, templates/distribution/_helpers.tpl, templates/distribution/manifests/auth/resources/pomerium-policy.yml.tpl, templates/distribution/manifests/auth/secrets/pomerium.env.tpl, templates/distribution/manifests/monitoring/kustomization.yaml.tpl, templates/distribution/manifests/monitoring/patches/grafana.ini.tpl, templates/distribution/manifests/monitoring/resources/ingress-infra.yml.tpl, templates/distribution/scripts/pre-apply.sh.tpl, tests/schemas/private/ekscluster-kfd-v1alpha2/001-ok.yaml, tests/schemas/private/ekscluster-kfd-v1alpha2/003-no.yaml, tests/schemas/private/ekscluster-kfd-v1alpha2/003-ok.yaml, tests/schemas/public/ekscluster-kfd-v1alpha2/001-ok.yaml, tests/schemas/public/ekscluster-kfd-v1alpha2/003-no.yaml, tests/schemas/public/ekscluster-kfd-v1alpha2/003-ok.yaml
- Changed `pomerium-policy.yaml` template to configure default routes based on `furyctl.yaml` modules.
- Added `routes` field to allow custom routes, replaces the old `policy` string field.
- Added `defaultRoutesPolicy` field to allow the customization of the policy field of the default routes, defaults to the current settings.
- Added `SIGNING_KEY` to Pomerium secrets.
- Removed duplicated schema code by creating a shared json imported in all schema kinds.
- Added `usersRoleAttributePath` and `basicAuthIngress` Grafana setting. 
```yaml
spec:
distribution:
modules:
monitoring:
grafana:
usersRoleAttributePath: contains(groups[*], 'product') && 'Admin' || contains(groups[*], 'engineering') && 'Editor' || 'Viewer'
basicAuthIngress: false
auth:
pomerium:
secrets:
COOKIE_SECRET: xxxx …
```
=> Add new schema fields to configure Pomerium

templates/distribution/manifests/ingress/resources/ingress-infra.yml.tpl, templates/distribution/manifests/logging/resources/ingress-infra.yml.tpl, templates/distribution/manifests/monitoring/resources/ingress-infra.yml.tpl, templates/distribution/manifests/opa/resources/ingress-infra.yml.tpl, templates/distribution/manifests/tracing/resources/ingress-infra.yml.tpl
Hello guys 👋 
This proposal aims to add the annotation `forecastle.stakater.com/group` to ingresses when we use Pomerium.
In this way we can have a web view similar to this one, even if all ingresses are in the same namespace.
I hope you like it 😄
=> Add Forecastle groups in ingress with SSO enabled

templates/distribution/manifests/monitoring/kustomization.yaml.tpl, templates/distribution/manifests/monitoring/resources/haproxy-scrapeConfig.yaml.tpl, templates/distribution/manifests/monitoring/resources/prometheus-agent/prometheus-agent.yaml.tpl, templates/distribution/scripts/pre-apply.sh.tpl, templates/kubernetes/onpremises/haproxy.cfg.tpl
enable metrics scraping from the haproxy loadbalancers and deploy the dashboards and alerts for haproxy from the monitoring module.
Note: I was unsure on setting some auth on the prometheus endpoint. Being that the 8405 port most likely will be accessible only from the inside I think that is enough. But let me know what you think.
> [!WARNING]
> This PR depends on the PR that adds the `haproxy` package to the monitoring module:
> - https://github.com/sighupio/fury-kubernetes-monitoring/pull/179
>
> And it is also has been rebased on the following PR that introduces PrometheusAgent mode that we needed to consider:
> - #228
=> feature(onprem): enable haproxy monitoring

.drone.yml, Furyfile.yaml, README.md, defaults/ekscluster-kfd-v1alpha2.yaml, defaults/kfddistribution-kfd-v1alpha2.yaml, defaults/onpremises-kfd-v1alpha2.yaml, docs/COMPATIBILITY_MATRIX.md, docs/releases/v1.27.8.md, docs/releases/v1.28.3.md, docs/releases/v1.29.3.md, docs/schemas/ekscluster-kfd-v1alpha2.md, docs/schemas/kfddistribution-kfd-v1alpha2.md, docs/schemas/onpremises-kfd-v1alpha2.md, docs/upgrades/README.md, kfd.yaml, pkg/apis/ekscluster/v1alpha2/private/schema.go, pkg/apis/ekscluster/v1alpha2/public/schema.go, pkg/apis/kfddistribution/v1alpha2/public/schema.go, pkg/apis/onpremises/v1alpha2/public/schema.go, schemas/private/ekscluster-kfd-v1alpha2.json, schemas/public/ekscluster-kfd-v1alpha2.json, schemas/public/kfddistribution-kfd-v1alpha2.json, schemas/public/onpremises-kfd-v1alpha2.json, templates/distribution/manifests/auth/secrets/dex.yml.tpl, tests/e2e-kfddistribution-upgrades.sh, tests/e2e/kfddistribution-upgrades/furyctl-init-cluster-1.29.3.yaml
- prepare releases v1.29.3 v1.28.3 and v1.27.8 including:
- Ingress 2.3.3 that fixes a CVE
- Configurable Dex expiration times for ID token and signing key
- improvements to some docs like the comp matrix
- bump e2e tests
Related PRs:
- #249 (already merged into this PR)
- https://github.com/sighupio/fury-kubernetes-ingress/pull/129
- https://github.com/sighupio/furyctl/pull/535
Note: I tagged `v1.29.3-rc.1` to run the e2e tests
=> feat: v1.29.3

templates/distribution/scripts/apply.sh.tpl
fix an issue in the `yq` filtering command used in the apply script that was excluding scrapeConfigs together with `AlertmanagerConfigs` when `distribution.modules.monitoring.alertmanager.installDefaultRules` was set to `false`.
Now it only filters out `AlertmanagerConfig` resources.
>[!NOTE]
> - For 1.29.3, 1.29.2, 1.28.2, and 1.27.7 this has been patched in furyctl distro-patches.
> - For 1.28.3 and 1.27.8 the fix is already included in the distro release.
=> fix(templates): don't filter out scrapeConfigs

docs/releases/v1.27.9.md, docs/releases/v1.28.4.md, docs/releases/v1.29.4.md, docs/schemas/ekscluster-kfd-v1alpha2.md, docs/schemas/kfddistribution-kfd-v1alpha2.md, docs/schemas/onpremises-kfd-v1alpha2.md, pkg/apis/ekscluster/v1alpha2/private/schema.go, pkg/apis/ekscluster/v1alpha2/public/schema.go, pkg/apis/kfddistribution/v1alpha2/public/schema.go, pkg/apis/onpremises/v1alpha2/public/schema.go, schemas/private/ekscluster-kfd-v1alpha2.json, schemas/public/ekscluster-kfd-v1alpha2.json, schemas/public/kfddistribution-kfd-v1alpha2.json, schemas/public/onpremises-kfd-v1alpha2.json, templates/distribution/scripts/apply.sh.tpl, templates/kubernetes/onpremises/hosts.yaml.tpl
Added an optional parameter to configure the registry.
```yaml
spec:
distribution:
common:
registry: myregistry.mydomain.ext
...
kubernetes:
advanced:
registry: myregistry.mydomain.ext
```
Related to https://github.com/sighupio/furyctl/pull/537.
=> feat: add support for custom registry

docs/schemas/onpremises-kfd-v1alpha2.md, pkg/apis/onpremises/v1alpha2/public/schema.go, schemas/public/onpremises-kfd-v1alpha2.json, templates/config/onpremises-kfd-v1alpha2.yaml.tpl
- Add missing description to the schema fields.
- Change redundant descriptions.
- Add specific ingress overrides for Auth module.
- Improve (a little) the configuration template for on-prem.
> [!NOTE]
> Once we reviewed and merged this PR I'll proceed to re-generate the markdown docs and port the improvements to the other schemas. I did not do it in this same PR to minimise the noise, most of the schema fields descriptions overlap.
=> fix(schemas/on-premises): add missing descriptions to schema

templates/kubernetes/onpremises/hosts.yaml.tpl
=> fix(on-prem): use the `.spec.kubernetes.advanced.users.org` parameter for kubernetes users creation

docs/schemas/onpremises-kfd-v1alpha2.md, schemas/public/onpremises-kfd-v1alpha2.json
Allow creating on-premises clusters with only control-plane hosts and no additional nodes, for minimal cluster installations.
=> feat(on-premises): allow clusters without nodes

templates/distribution/manifests/ingress/kustomization.yaml.tpl, templates/distribution/scripts/pre-apply.sh.tpl
- Don't create `ingress-nginx-global-tls-cert` secret in `ingress-nginx` namespace when `nginx.tls.provider` is set to `secret` and `nginx.type: none` at the same time, it results in an error bacause the namespace does not exist.
- Migration for `nginx.type -> none`: ingresses in `kube-system` namespace (dex, gangway, hubble) were not being deleted. Delete all the ingresses in the `kube-system` namespace as part of the migration.
> [!NOTE]
> This PR is branched off #280 because it modifies some of the same files. You may see changes from both PRs here until 280 is merged.
=> fix(templates/ingress): nginx type none and tls secret, migration to none

schemas/public/spec-plugins.json
This is needed to disable helmfile validation (helm diff command) during installation, when installin CR that depends on CRD deployed by the chart itself (for example, the netapp trident driver)
=> fix: adding a new field on plugins spec to permit a new field

templates/kubernetes/ekscluster/terraform/main.auto.tfvars.tpl
As the `ami_owners` has been introduced in https://github.com/sighupio/fury-eks-installer/pull/80 now it's possible to use the value of `nodePools.ami.owner` in the eks installer
=> fix eks terraform template with missing ami_owners

templates/distribution/manifests/auth/resources/pomerium-policy.yml.tpl
Fix login in Pomerium routes definition, minio-tracing route was not being added when logging is set to `none`.
=> fix(templates/auth/pomerium): route for minio-tracing missing

templates/distribution/manifests/logging/resources/ingress-infra.yml.tpl, templates/distribution/manifests/monitoring/resources/ingress-infra.yml.tpl, templates/distribution/manifests/tracing/resources/ingress-infra.yml.tpl
This PR is to better specify minio's tls secret name.
Now the secret is called `minio-tls` for all the variants: logging, monitoring and tracing. Most of the time this is not a problem.
The issue that we get as of today is when auth is `sso`, so all ingresses are deployed in `pomerium` namespace and in this case they are sharing all the same tls secret (and certificate).
Changing all the names solves the issue.
=> fix(minio): more specific tls secret name

templates/distribution/scripts/pre-apply.sh.tpl
Remove `minio-monitoring` ingress when switching from `.spec.distribution.modules.monitoring.type: mimir` to `.spec.distribution.modules.monitoring.type: none`.
=> fix(migrations): remove minio-monitoring ingress when migrating `mimir` -> `none`

kfd.yaml, templates/distribution/manifests/tracing/patches/minio.root.env.tpl, templates/distribution/manifests/tracing/patches/tempo.yaml.tpl
- bump tracing version to v1.1.0.
- drop deprecated fields from tempo's configuration file template.
- align nomenclature in minio's root credentials to follow the breaking change introduced in the release of the module.
> [!NOTE]
> Creating PR as draft waiting for confirmation on 1.28 compatibility
=> feat(tracing): bump to v1.1.0

kfd.yaml
This PR updates the networking module to v2.0.0-rc.1 version.
There are no changes on the template or the distribution, just applying the new version will work. It's a major version because we removed calico manifests only package from the module (not used by the distribution itself).
Cilium:
Calico:
=> Feat(networking): update networking to v2.0.0 rc

kfd.yaml, templates/distribution/manifests/monitoring/resources/ingress-infra.yml.tpl, templates/distribution/manifests/monitoring/resources/prometheus-agent/prometheus-agent.yaml.tpl
- Update kfd.yaml to use monitoring v3.3.0-rc1.
- Update templates to align the scrapeConfigs to what has been done in the monitoring module. We pick all of them instead of selecting an specific label.
- No other changes are necessary. Upgrade does not need special steps to follow other than the usual apply of the new manifests.
Bonus:
- Fix a bug on minio-monitoring ingress template. Ingress was pointing to the service of minio-tracing instead of monitoring. Fixes #308
=> feat(monitoring): update to monitoring v3.3.0-rc.1

kfd.yaml
- bump Auth module to `v0.4.0-rc.0`
No other changes are necessary to switch to this version, no migrations or upgrade paths are necessary.
=> feat(auth): bump to v0.4.0-rc.0

pkg/apis/ekscluster/v1alpha2/private/schema.go, pkg/apis/ekscluster/v1alpha2/public/schema.go, schemas/private/ekscluster-kfd-v1alpha2.json, schemas/public/ekscluster-kfd-v1alpha2.json
- Improve description fields for EKS NodePools AMI configuration
- Improve dependencies definitions in schema, so mutually exclusive options are considered: now the schema does not let you set `ami.type` at the same time than `ami.id`&`ami.owner`; as viceversa.
> [!NOTE]
> You can focus on the `schemas/public/ekscluster-kfd-v1alpha2.json` file for the review. The rest is autogenerated.
=> fix(schemas/eks): improvements for AMI fields

docs/network-policies/modules/logging/README.md, templates/distribution/manifests/auth/policies/pomerium.yaml.tpl, templates/distribution/manifests/logging/policies/opensearch-dashboards.yaml.tpl, templates/distribution/manifests/logging/policies/opensearch.yaml.tpl, templates/distribution/manifests/monitoring/policies/minio.yaml.tpl
- Add netpol for allowing traffic from ingresses to Minio Monitoring in single, dual and SSO.
- Use new labels for OpenSearch and OpenSearch-Dashboard job pods
- Update readme with this changes
=> fix(netpols): minio-monitoring ingress and opensearch jobs

banners/ekscluster.md, banners/kfddistribution.md, banners/onpremises.md, defaults/ekscluster-kfd-v1alpha2.yaml, docs/schemas/ekscluster-kfd-v1alpha2.md, docs/schemas/kfddistribution-kfd-v1alpha2.md, docs/schemas/onpremises-kfd-v1alpha2.md, pkg/apis/ekscluster/v1alpha2/private/schema.go, pkg/apis/ekscluster/v1alpha2/public/schema.go, pkg/apis/kfddistribution/v1alpha2/public/schema.go, pkg/apis/onpremises/v1alpha2/public/schema.go, schemas/private/ekscluster-kfd-v1alpha2.json, schemas/public/ekscluster-kfd-v1alpha2.json, schemas/public/kfddistribution-kfd-v1alpha2.json, schemas/public/onpremises-kfd-v1alpha2.json, templates/config/ekscluster-kfd-v1alpha2.yaml.tpl
Port to the `EKSCluster` and `KFDDistribution` schemas documentation the improvements done for the `on-prem` schema in #268. Some minor improvements to on-premises too.
For review purposes you can focus on the files in the folders:
- `banners/`
- `schemas/public/`
The rest of the files are generated using `make generate-go-models` and `make generate-docs`.
Closes https://github.com/sighupio/product-management/issues/543 https://github.com/sighupio/furyctl/issues/287
> [!NOTE]
> In order to generate the markdown files you need a patched version of `md-gen` otherwise the markdown generation fails with a type assertion error.:
> - https://github.com/sighupio/md-gen/pull/2
=> feat(docs/schema): improve eks, kfdisitribution schema docs

.drone.yml
Trigger the release pipeline only when needed, i.e. when tagging with a tag starting with `v`.
Before, the release pipeline was always triggered when tagging, even when tagging to only run the e2e tests without wanting to do a release, so there may be no release notes available. In this case the CI could fail because it will not find the release notes file.
=> chore(ci): trigger release pipeline only when needed

docs/releases/unreleased.md, schemas/public/onpremises-kfd-v1alpha2.json, templates/kubernetes/onpremises/create-playbook.yaml.tpl, templates/kubernetes/onpremises/hosts.yaml.tpl
- Added the possibility to set labels and annotations for both the control-plane nodes and the regular nodes.
- Added new (optional) fields to the on-prem schema, with pattern validation.
- Added logic to the Ansible playbook to set the labels and annotations on the nodes, and also remove them when deleted from the furyctl.yaml file, checking against the saved state.
This PR extends the logic we had for setting the nodes roles and adds the possibility to set custom labels and annotations to both control-plane nodes and regular nodes for on-premises clusters.
We use `kubectl` commands instead of kubeadm/kubelet configuration because:
- kubeadm/kubelet configuration is set when joining the node.
- kubeadm/kubelet configuration does not support setting some special labels, like the one that …
=> feat(on-premises): node labels and annotations

docs/releases/unreleased.md, templates/distribution/scripts/pre-apply.sh.tpl
When switching policy type from `kyverno` to `none`, delete first the objects using the APIs of the CRDs and then the CRDs. Otherwise we could sometimes end up in a race condition where the objects cannot be deleted because the APIs are not available anymore.
Closes #335
Instead of building the whole kustomize base for Kyverno and piping it to the kubectl delete, the command that deletes Kyverno resources has been split into 2 commands that are applied separately, one after the other: `policies` and `core`, respectively.
See the issue #335 for more details on the reasoning behind this PR.
None
None, notice that now that we switched to kapp, the migration could be dropped entirely and let kapp handle the deletion.
=> fix(migrations/policy): delete objects before crds

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
Minor improvements to the Issues and PR templates.
Issues:
- Use the new issue `type` instead of labels for the type of isse (bug, feature)
- Use markdown level 3 titles instead of bold for the sections of the body (like we already did in the PR template)
- Improve wording
PRs:
- Improve wording and formatting
None
None
None
None
=> chore(issue and pr template): minor improvement

docs/releases/unreleased.md, kfd.yaml, templates/distribution/scripts/apply.sh.tpl, templates/distribution/scripts/delete.sh.tpl, templates/plugins/scripts/apply.sh.tpl
Upgrade Kustomize from version 3.10 to the latest version (at the time of writing this is 5.6.0).
Relates: https://github.com/sighupio/product-management/issues/630
Since we were falling a little behind with the Kustomize versions, we are now updating to version v5 of Kustomize.
`--load_restrictor` flag is now `--load-restrictor`.
Follow implementation on `furyctl` too.
=> feat(kustomize): update to version v5 (5.6.0)

docs/releases/unreleased.md, docs/schemas/onpremises-kfd-v1alpha2.md, kfd.yaml, pkg/apis/onpremises/v1alpha2/public/schema.go, rules/onpremises-kfd-v1alpha2.yaml, schemas/public/onpremises-kfd-v1alpha2.json, templates/kubernetes/onpremises/54.upgrade-etcd.yaml.tpl, templates/kubernetes/onpremises/55.upgrade-control-plane.yml.tpl, templates/kubernetes/onpremises/98.cluster-certificates-renewal.yaml.tpl, templates/kubernetes/onpremises/create-playbook.yaml.tpl, templates/kubernetes/onpremises/delete-playbook.yaml.tpl, templates/kubernetes/onpremises/hosts.yaml.tpl, templates/preflight/onpremises/hosts.yaml.tpl
This PR introduces support for a dedicated etcd cluster deployment on the OnPremises provider.  
The changes allow defining separate etcd nodes from the control plane (`master`) nodes. 
Closes: [#548](https://github.com/sighupio/product-management/issues/548)
Relates: [#116](https://github.com/sighupio/fury-kubernetes-on-premises/pull/116) [#146](https://github.com/sighupio/kfd-docs/pull/146) [#568](https://github.com/sighupio/furyctl/pull/568)
The main changes introduced in this PR:  
- Schema update (`onpremises-kfd-v1alpha2.md`, `schema.go`, `onpremises-kfd-v1alpha2.json`) to include the new `.spec.kubernetes.etcd` key.  This is optional.
- New Ansible playbook (`54.upgrade-etcd.yaml.tpl`) to centralize etcd nodes upgrade and certificates renewal.
- Updating the existing playbooks …
=> feat(on-prem): support etcd cluster provisioning on dedicated nodes

docs/releases/unreleased.md, templates/config/ekscluster-kfd-v1alpha2.yaml.tpl, templates/config/kfddistribution-kfd-v1alpha2.yaml.tpl, templates/config/onpremises-kfd-v1alpha2.yaml.tpl
This PR fixes two small issues with the template config files that `furyctl create config` uses:
- Link to documentation in the heading: correction after the refactoring of the documentation website
- Keepalived passphrase: after recent changes in the schema, the `spec.kubernetes.loadBalances.keepalived.passphrase` parameter in the OnPremises template needed to be changed
When you create a `furyctl.yaml` config file using `furyctl create config`, the heading is directing users to an old documentation link that does not work anymore, because the refactoring of the documentation site changed the path of the Providers' explanations.
Also, after the [recent changes to the schema](https://github.com/sighupio/fury-distribution/commit/8a647a748032d3b99f89fdc9be63a7f569ebb800), the template …
=> fix: small fixes in template config files

kfd.yaml
Bump kapp to latest version 0.64.1, that includes some security patching and no functional modifications:
https://github.com/carvel-dev/kapp/releases/tag/v0.64.1
See summary
None
Being that there are no functional changes and is a patch release, I think we can test this in the release process.
None
=> feat(kapp): bump to 0.64.1

docs/schemas/ekscluster-kfd-v1alpha2.md, docs/schemas/kfddistribution-kfd-v1alpha2.md, docs/schemas/onpremises-kfd-v1alpha2.md, pkg/apis/onpremises/v1alpha2/public/schema.go, schemas/public/onpremises-kfd-v1alpha2.json, templates/kubernetes/onpremises/hosts.yaml.tpl
This PR adds support for kubeadm and kubelet reconfiguration to the OnPremises provider.
Closes: [#634](https://github.com/sighupio/product-management/issues/634)
This update adds `kubeletConfiguration` field at three different levels:
- Global level (spec.kubernetes.advanced.kubeletConfiguration).
- Master nodes level (spec.kubernetes.masters.kubeletConfiguration).
- Worker node groups level (spec.kubernetes.nodes.kubeletConfiguration).
Also adds missing `apiServerCertSANs` field for kubeadm reconfiguration, under spec.kubernetes.advanced key.
None.
```yaml
apiVersion: kfd.sighup.io/v1alpha2
kind: OnPremises
metadata:
name: test
spec:
distributionVersion: v1.32.0
kubernetes:
advanced:
apiServerCertSANs:
- my.domain.com
- other.domain.net
```
```yaml
apiVersion: kfd.sighup.io/v1alpha2 …
```
=> feat(on-premises): add kubeadm and kubelet fields

templates/distribution/terraform/eks-addons.tf.tpl
This PR fix empty common nodeSelectors and tolerations in EKS addons terraform template.
Relates: https://github.com/sighupio/distribution/pull/367
Edit EKS addon terraform template
=> fix(templates,distribution): don't set common tolerations and nodeSelector when empty

templates/distribution/manifests/dr/resources/etcd-backup-pvc.yml.tpl, templates/distribution/manifests/dr/secrets/rclone.conf.tpl
This PR fixes a small rendering problem found while testing EKS.
During the distribution phase the EKS provider failed because it tried to render a file which contained invalid fields. This is fixed by avoiding to render the etcd-backup files when on EKS.
None.
None.
None.
=> Fix etcd-backup while on EKS provider

docs/schemas/ekscluster-kfd-v1alpha2.md, docs/schemas/kfddistribution-kfd-v1alpha2.md, docs/schemas/onpremises-kfd-v1alpha2.md, pkg/apis/ekscluster/v1alpha2/private/schema.go, pkg/apis/ekscluster/v1alpha2/public/schema.go, pkg/apis/kfddistribution/v1alpha2/public/schema.go, pkg/apis/onpremises/v1alpha2/public/schema.go, schemas/private/ekscluster-kfd-v1alpha2.json, schemas/public/ekscluster-kfd-v1alpha2.json, schemas/public/kfddistribution-kfd-v1alpha2.json, schemas/public/onpremises-kfd-v1alpha2.json
Update documentation for the `tsdbStartDate` field in the Loki module to clarify that the change from BoltDB to TSDB and schema v11 to v13.
Also, correct the wording to indicate that the field is immutable once set and should be set to the past before upgrading to certain versions.
Fix the mentioned version for 1.30.x
NOTE: this PR includes `make generate-go-models` and `make generate-docs`.
Relates: #371 
As per summary
None
- Maybe we should set a default for the `tsdbStartDate` field, now that the migration is done.
- Port these changes to the docs site.
=> docs(schemas): update description for loki's tsdbDate field

templates/preflight/onpremises/verify-playbook.yaml, templates/preflight/onpremises/verify-playbook.yaml.tpl
This PR addresses a bug preventing control planes nodes array to be marked as immutable under the OnPremises provider. Control plane nodes were set as immutable in the 1.31.1 release cycle because we don't have any support to scale the etcd cluster with the number of control plane nodes. Moreover, the etcd cluster can potentially be placed on control plane nodes or set-up on separate machines, adding further cases to the etcd scaling support, which at the moment we don't support.
Closes: #360 
Refers:  https://github.com/sighupio/product-management/issues/651
Immutable behaviour in the OnPremises provider is checked during the preflight phase, after having checked the availability of the hosts set in the `.spec.kubernetes.masters.hosts.*` keys in `furyctl.yaml`. The availability of the …
=> Fix immutability on control planes

templates/distribution/manifests/ingress/kustomization.yaml.tpl
With this PR network policies for the Ingress module are included in the root `kustomization.yaml` only when at least one condition between `spec.distribution.modules.ingress.nginx.tls.provider: certManager` or `spec.distribution.modules.ingress.nginx.type != none` is met and `spec.distribution.common.networkPoliciesEnabled` is true.
Closes: [#365](https://github.com/sighupio/distribution/issues/365)
With the migration from Kustomize v3 to v5, the behavior around empty `kustomization.yaml` files has changed.
In Kustomize v3, a file with an empty resources list was silently ignored, in Kustomize v5 the same file causes an error during the build.
To fix this, we now include the network policies only when network policies are enabled and at least one of the above conditions applies.
None. …
=> fix(templates): add condition for network policies in Ingress module

defaults/ekscluster-kfd-v1alpha2.yaml, defaults/kfddistribution-kfd-v1alpha2.yaml, defaults/onpremises-kfd-v1alpha2.yaml, docs/releases/unreleased.md, docs/schemas/ekscluster-kfd-v1alpha2.md, docs/schemas/kfddistribution-kfd-v1alpha2.md, docs/schemas/onpremises-kfd-v1alpha2.md, pkg/apis/ekscluster/v1alpha2/private/schema.go, pkg/apis/ekscluster/v1alpha2/public/schema.go, pkg/apis/kfddistribution/v1alpha2/public/schema.go, pkg/apis/onpremises/v1alpha2/public/schema.go, schemas/private/ekscluster-kfd-v1alpha2.json, schemas/public/ekscluster-kfd-v1alpha2.json, schemas/public/kfddistribution-kfd-v1alpha2.json, schemas/public/onpremises-kfd-v1alpha2.json, templates/distribution/manifests/logging/patches/loki-config.yaml.tpl
This PR adds support for logs retention in the Loki configuration using the compactor component, as specified in the Loki [official documentation](https://grafana.com/docs/loki/latest/operations/storage/retention/). This implementation follows the recommended approach for TSDB-based storage.
Closes: [https://github.com/sighupio/module-logging/issues/177](https://github.com/sighupio/module-logging/issues/177)
The change includes:
- Support for global retention via the `retention_period` setting under `limits_config`
- Removal of `table_manager` (deprecated) configuration block
- Usage of the existing `persistentvolumeclaim/data-loki-distributed-compactor` as the working directory for the compactor
None.
None.
=> feat(logging): add support for parametric logs retention in Loki

templates/distribution/scripts/apply.sh.tpl
This PR fixes an issue on some architectures, where the `sh` binary isn't symlinked and doesn't behave like `bash`.\
This removes any non-POSIX syntax in the `apply.sh` file.
Nothing.
Make `bash` the default.
=> Make `apply.sh` POSIX compatible

docs/releases/unreleased.md, templates/distribution/scripts/pre-apply.sh.tpl
Fix migrations of logging from * to none when monitoring is disabled.
logging migrations to none (i.e. deleting logging resources) failed if _monitoring_ was none because we were trying to delete resources using the monitoring.coreos.com/v1 API that was not available. This fix filters out these type of resources from the deletion.
Closes: #400 
Relates: discovered while debugging #398 
See summary
None
None
=> fix(migrations/logging): to none without monitoring

defaults/ekscluster-kfd-v1alpha2.yaml, defaults/kfddistribution-kfd-v1alpha2.yaml, defaults/onpremises-kfd-v1alpha2.yaml, docs/schemas/ekscluster-kfd-v1alpha2.md, docs/schemas/kfddistribution-kfd-v1alpha2.md, docs/schemas/onpremises-kfd-v1alpha2.md, pkg/apis/ekscluster/v1alpha2/private/schema.go, pkg/apis/ekscluster/v1alpha2/public/schema.go, pkg/apis/kfddistribution/v1alpha2/public/schema.go, pkg/apis/onpremises/v1alpha2/public/schema.go, schemas/private/ekscluster-kfd-v1alpha2.json, schemas/public/ekscluster-kfd-v1alpha2.json, schemas/public/kfddistribution-kfd-v1alpha2.json, schemas/public/onpremises-kfd-v1alpha2.json, templates/distribution/manifests/logging/patches/loki-config.yaml.tpl
Renamed the `retentionPeriod` schema field since on all other fields for the same purpose we use `retentionTime`.
Relates: [sighupio/distribution/pull/396](https://github.com/sighupio/distribution/pull/396)
See above.
None.
Same tests describe [here](https://github.com/sighupio/distribution/pull/396)
None.
=> chore(schema): align Loki retentionPeriod with the naming convention

docs/releases/unreleased.md, templates/distribution/manifests/ingress/kustomization.yaml.tpl, templates/distribution/manifests/ingress/resources/cert-manager-clusterissuer.yml.tpl
- Don't fail template rendering when cert-manager's solvers are not set.
- Always patch cert-manager's resources to use the nodeSelectors and Tolerations 
Fixes #211
- Being that the default value for `ingress.tls.provider` is `certManager` without a `clusterIssuer.type` set, and there is not a default value for solvers, the template would fail trying to access the solvers key in the configuration. Changed to check if the key exists instead.
- When deploying the default configuration with `ingress.nginx.type: none` and `tls.provider` **not** set (so, cert-manager as per the defaults); the patch for adding `nodeSelectors` and `Tolerations` was not being applied. Now we apply always the patch, because cert-manager is always deployed.
None
None
=> fix(templates): ingress cert-manager solvers

docs/releases/unreleased.md, templates/distribution/manifests/auth/resources/ingress-infra.yml.tpl
Add labels and annotations to show an entry for Gangplank on Forecastle's Directory
See summary
None
None
=> fix(templates/auth): show Gangplank in Forecastle

rules/ekscluster-kfd-v1alpha2.yaml, rules/kfddistribution-kfd-v1alpha2.yaml, rules/onpremises-kfd-v1alpha2.yaml
fix immutability rules for `.spec.distribution.modules.logging.loki.tsdbStartDate`
it should be possible to migrate from `logging.type: none` to `logging.type: loki`
Closes: https://github.com/sighupio/distribution/issues/398
Relates:
- https://github.com/sighupio/furyctl/pull/610
added new safe reducer to:
- `rules/ekscluster-kfd-v1alpha2.yaml`
- `rules/kfddistribution-kfd-v1alpha2.yaml`
- `rules/onpremises-kfd-v1alpha2.yaml`
none
- migrating from logging.type: none to logging.type: loki -> does not get blocked
- migrating from logging.type: loki to logging.type: opensearch -> does not get blocked
- migrating from logging.type: loki to logging.type: none -> does not get blocked
- migrating from logging.type: loki to logging.type: opensearch -> gets blocked, unsupported
- regression test: …
=> fix: tsdbStartDate immutability when migrating from logging.type: none to logging.type: loki

.drone.yml, tests/e2e/onpremises-upgrades/0.local-tofu-run.yaml, tests/e2e/onpremises-upgrades/1.remote-furyctl-exec.yaml, tests/e2e/onpremises-upgrades/2.remote-furyctl-exec-upgrade.yaml, tests/e2e/onpremises-upgrades/3.local-tofu-destroy.yaml, tests/e2e/onpremises-upgrades/access.tf, tests/e2e/onpremises-upgrades/ansible.cfg, tests/e2e/onpremises-upgrades/e2e-onpremises.sh, tests/e2e/onpremises-upgrades/firewall.tf, tests/e2e/onpremises-upgrades/helper.bash, tests/e2e/onpremises-upgrades/hosts.yaml, tests/e2e/onpremises-upgrades/main.tf, tests/e2e/onpremises-upgrades/network.tf, tests/e2e/onpremises-upgrades/nodes.tf, tests/e2e/onpremises-upgrades/output.tf, tests/e2e/onpremises-upgrades/to_copy/00.prepare-hosts.yaml, tests/e2e/onpremises-upgrades/to_copy/create_ingress_certs.sh, tests/e2e/onpremises-upgrades/to_copy/encrypted-secret-config.yaml, tests/e2e/onpremises-upgrades/to_copy/haproxy-additional.cfg, tests/e2e/onpremises-upgrades/variables.tf, tests/e2e/onpremises/1.remote-furyctl-exec.yaml, tests/e2e/onpremises/output.tf
This PR adds e2e tests to test onpremises cluster upgrades.
The overall goal of this PR is to have a baseline testing on the OnPremises provider, that was tested manually on each release.
**I also changed the behaviour of the standard onpremises e2e test, using the current distribution commit folder to create the cluster instead of an RC tag.**
- None
- https://ci.sighup.io/sighupio/distribution/3252/1/5
=> Feat: add onpremises e2e upgrade tests

defaults/ekscluster-kfd-v1alpha2.yaml, defaults/kfddistribution-kfd-v1alpha2.yaml, defaults/onpremises-kfd-v1alpha2.yaml, docs/schemas/ekscluster-kfd-v1alpha2.md, docs/schemas/kfddistribution-kfd-v1alpha2.md, docs/schemas/onpremises-kfd-v1alpha2.md, pkg/apis/ekscluster/v1alpha2/private/schema.go, pkg/apis/ekscluster/v1alpha2/public/schema.go, pkg/apis/kfddistribution/v1alpha2/public/schema.go, pkg/apis/onpremises/v1alpha2/public/schema.go, schemas/private/ekscluster-kfd-v1alpha2.json, schemas/public/ekscluster-kfd-v1alpha2.json, schemas/public/kfddistribution-kfd-v1alpha2.json, schemas/public/onpremises-kfd-v1alpha2.json, templates/config/ekscluster-kfd-v1alpha2.yaml.tpl, templates/config/kfddistribution-kfd-v1alpha2.yaml.tpl, templates/config/onpremises-kfd-v1alpha2.yaml.tpl
Since we have Loki v3 that does not support BoltDB anymore and TSDB is the default, we don't need to ask the user for a migration date anymore.
We set a default value for the tsdbStartDate in the past, so all the new logs will be written usign TSDB.
We had set the immutability rules for this field in #409
Relates:
- #409 
As per summary
None
None
=> feat(logging): set default value for Loki's tsdbStartDate

docs/releases/v1.30.2.md, docs/releases/v1.31.1.md, docs/releases/v1.32.0.md
Add warning to use latest furyctl version when upgrading to version v1.32.0 of the distribution.
Relates:
There was an issue when upgrading to version 1.32.0 in the OnPremises provider when gatekeeper was enabled. This PR makes an effort to document that.
None.
None.
None.
=> Add warning in release note for v1.32.0

defaults/ekscluster-kfd-v1alpha2.yaml, defaults/kfddistribution-kfd-v1alpha2.yaml, defaults/onpremises-kfd-v1alpha2.yaml, docs/releases/unreleased.md, docs/schemas/onpremises-kfd-v1alpha2.md, pkg/apis/onpremises/v1alpha2/public/schema.go, schemas/public/onpremises-kfd-v1alpha2.json, templates/distribution/manifests/logging/kustomization.yaml.tpl, templates/distribution/manifests/logging/patches/logging-operated-resources.yaml.tpl, templates/distribution/manifests/logging/patches/loki-resources.yml.tpl
- Add configuration fields to the schemas to allow setting resources to Logging Operator's Fluentd and Fluentbit.
- Add configuration field to set Logging Operator's Fluentd replica count.
- Adjust templates to use the new fields.
- Update logging's kustomization.yaml file to use `patches` and drop deprecated syntax. Make logic a little clearer (hopefully)
- Update related documentation.
Relates:
- https://github.com/sighupio/module-logging/pull/191 
We've seen lately that for production clusters the defaults were not enough and patching the resources requests and specially limits for the loggging stack components was a common use case.
This PR adds missing parameters to configure the logging stack from the furyctl.yaml file, under the `spec.distribution.modules.logging.operator` key, one …
=> feat(logging): allow to set Fluentd and Fluentbit's resouces

docs/releases/unreleased.md, schemas/public/spec-plugins.json
Validate kustomize plugins name pattern with what kapp expects at schema level so errors are catch soon and avoid runtime errors after a (maybe long) apply.
See summary.
Note: linting failures are unrelated to this PR.
None
None
=> fix(schemas): validate kustomize plugin names pattern

templates/kubernetes/ekscluster/terraform/main.auto.tfvars.tpl
Fix missing tags variable assignment in EKS cluster Terraform template causing resources to be created without proper tagging.
Closes: [sighupio/product-management/issues/662](https://github.com/sighupio/product-management/issues/662)
Fixes a bug where the `tags` variable was defined in `variables.tf` and referenced in `main.tf.tpl` but not populated in `main.auto.tfvars.tpl`, resulting in an empty tags map being passed to the EKS module. 
None.
It will be tested during the execution of the distro's e2e.
None.
=> fix(terraform): missing tags variable assignment in ekscluster template

templates/distribution/manifests/logging/kapp-configs/logging-operator-crd.yaml, templates/distribution/manifests/logging/kapp-configs/loki-hpa.yaml, templates/distribution/manifests/logging/kustomization.yaml.tpl
Add kapp configuration definitions to avoid overriding the replicas number set by the HPAs we deploy together with Loki.
Fixes #438
I took the chance and also added an exception to a field of the Logging Operator CRD that was being removed by kapp on every apply. This did not have the impact that changing the replicas for Loki's components has, but I fixed it while I was at it.
None
There are other places where we could do the same probably.
=> fix: keep Loki replicas

docs/schemas/kfddistribution-kfd-v1alpha2.md, docs/schemas/onpremises-kfd-v1alpha2.md, pkg/apis/kfddistribution/v1alpha2/public/schema.go, pkg/apis/onpremises/v1alpha2/public/schema.go, schemas/public/onpremises-kfd-v1alpha2.json, templates/kubernetes/onpremises/hosts.yaml.tpl
Add containerd TOML settings configuration for on-premises provider to allow customization of containerd runtime parameters.
Relates:
Exposes containerd configuration fields, already present on the on-premises installer, for environments requiring custom container runtime settings. All fields map to containerd config.toml parameters.
Schema additions:
- `spec.kubernetes.advanced.containerd.storageDir`: Containerd storage directory
- `spec.kubernetes.advanced.containerd.stateDir`: Containerd state directory
- `spec.kubernetes.advanced.containerd.systemdDir`: Containerd systemd service directory
- `spec.kubernetes.advanced.containerd.oomScore`: Containerd OOM score adjustment
- `spec.kubernetes.advanced.containerd.grpcMaxRecvMessageSize`: Containerd gRPC max receive message size in bytes
- …
=> feat(schemas/on-prem): add containerd TOML settings

templates/distribution/manifests/logging/policies/opensearch-dashboards.yaml.tpl
Align opensearch network policies with the label changes introduced in v5.2.0 for opensearch-darshboards.
Relates:
- https://github.com/sighupio/module-logging/pull/193
The labels for opensearch dashboard pods have changed with the update of OpenSearch in https://github.com/sighupio/module-logging/pull/193/files
This PR updates the labels selectors in the Logging network policies to the new values.
It also adds a new Ingress netpol, wihtout it incoming traffic to opensearch-master was being blocked.
None
None
=> fix(network-policies): align opensearch with latest changes

docs/releases/v1.33.0.md, docs/schemas/ekscluster-kfd-v1alpha2.md, docs/schemas/onpremises-kfd-v1alpha2.md, pkg/apis/ekscluster/v1alpha2/private/schema.go, pkg/apis/ekscluster/v1alpha2/public/schema.go, pkg/apis/onpremises/v1alpha2/public/schema.go, schemas/public/onpremises-kfd-v1alpha2.json, templates/kubernetes/onpremises/hosts.yaml.tpl
Refactor repository management configuration fields to eliminate ambiguity. Changes `manageRepositories` to `selfmanagedRepositories` with inverted logic to make the field name more descriptive.
Relates: [sighupio/distribution/pull/444](https://github.com/sighupio/distribution/pull/444)
- Renamed `manageRepositories` to `selfmanagedRepositories`
- Inverted logic:
- `selfmanagedRepositories: false` (default) when furyctl manages repositories automatically
- `selfmanagedRepositories: true` when user manages repositories externally
None.
None.
=> refactor: refactor repository management variables
