.drone.yml
.rules/.markdown-lint.yml
Furyfile.yml
README.md
docs/releases/v1.4.0.md
katalog/tests/config/kind-config-custom
katalog/tests/dr.sh
katalog/tests/helper.bash
katalog/tests/ingress.sh
katalog/tests/install.sh
katalog/tests/logging.sh
katalog/tests/monitoring.sh
katalog/tests/networking.sh
katalog/tests/opa.sh
kustomization.yaml
release-notes.py

Contains the release files to deploy Fury v1.4.0
Waiting for the CI: http://ci.sighup.io/sighupio/fury-distribution/109

Release v1.4.0

---

README.md

To be merged with Fury 1.23 Release

Add Kubernetes 1.23 Certified logo

---

README.md
docs/COMPATIBILITY_MATRIX.md
docs/VERSIONING.md
docs/releases/v1.21.0.md

In this PR we are adding information on the new KFD versioning scheme

docs: adding versioning and upgrade informations

---

templates/config/ekscluster-kfd-v1alpha2.yaml.tpl

As per title, added some comments on all the keys
closes sighupio/product-management#127
EDIT: I will open another PR to address #42 and #41

docs: add descriptions in the furyctl.yaml file

---

templates/config/ekscluster-kfd-v1alpha2.yaml.tpl
templates/distribution/manifests/auth/resources/pomerium-policy.yml.tpl
templates/distribution/manifests/logging/resources/ingress-infra.yml.tpl

fix: fix template (identation for pomerium/dex template, add baseDomain on auth, fix opensearch-dashboards key)

---

pkg/schema/ekscluster_kfd_v1alpha2.go
schemas/ekscluster-kfd-v1alpha2.json

Changelist:
- added baseDomain to spec.distribution.modules.auth in schema, required if auth.provider.type == "sso"
- regen go types from schema

feat: added baseDomain to spec.distribution.modules.auth

---

pkg/schema/ekscluster_kfd_v1alpha2.go
schemas/ekscluster-kfd-v1alpha2.json
templates/config/ekscluster-kfd-v1alpha2.yaml.tpl

Changelist:
- added nodePoolsLaunchKind and logRetentionDays to templates/config
- added nodePoolsLaunchKind and logRetentionDays to json schema
- generated new go file from schema
closes #49

Feat: added support to nodePoolsLaunchKind and logRetentionDays

---

templates/distribution/terraform/main.tf.tpl
templates/distribution/terraform/velero.tf.tpl

https://github.com/sighupio/furyctl/issues/303 was solved together with https://github.com/sighupio/furyctl/pull/315.

chore: draft better region handling in distribution templates

---

docs/upgrades/v1.24.0-to-v1.25.0.md

This PR adds improvement on the upgrade guide already added in the #69 PR

docs: improve upgrade guide

---

README.md
docs/COMPATIBILITY_MATRIX.md
docs/releases/v1.25.1.md
docs/upgrades/v1.24.0-to-v1.25.0.md
docs/upgrades/v1.25.0-to-v1.25.1.md
releases/v1.25.1/Furyfile.yml
releases/v1.25.1/kustomization.yaml

Feat/add 1.25.1

---

docs/COMPATIBILITY_MATRIX.md
docs/VERSIONING.md

docs: simplify compatibility matrix

---

pkg/config/model.go
pkg/schema/private/ekscluster_kfd_v1alpha2.go
pkg/schema/public/ekscluster_kfd_v1alpha2.go
schemas/private/ekscluster-kfd-v1alpha2.json
schemas/public/ekscluster-kfd-v1alpha2.json
templates/config/ekscluster-kfd-v1alpha2.yaml.tpl

Changelist:
- removes distributionVersion regex validation, now it needs just to be a string, in order to support branches AND SemVer ( tags )

Feat: added branches support on distribution version

---

pkg/config/model.go

feat: calculate checksums from archives

---

pkg/schema/private/ekscluster_kfd_v1alpha2.go
pkg/schema/public/ekscluster_kfd_v1alpha2.go
schemas/private/ekscluster-kfd-v1alpha2.json
schemas/public/ekscluster-kfd-v1alpha2.json

Changelist:
- added bucketNamePrefix to EKSCluster schema in .spec.Infrastructure.Vpn

feat: added support to bucketNamePrefix in VPN section

---

README.md
docs/COMPATIBILITY_MATRIX.md
docs/releases/v1.25.3.md
docs/upgrades/v1.25.2-to-v1.25.3.md
kfd.yaml
pkg/schema/private/ekscluster_kfd_v1alpha2.go
pkg/schema/public/ekscluster_kfd_v1alpha2.go
schemas/private/ekscluster-kfd-v1alpha2.json
schemas/public/ekscluster-kfd-v1alpha2.json
templates/distribution/terraform/main.tf.tpl

as per title, for now in draft

Feat/release 1.25.3

---

kfd.yaml
pkg/apis/config/model.go
templates/distribution/manifests/ingress/resources/ingress-infra.yml.tpl
templates/distribution/manifests/logging/resources/ingress-infra.yml.tpl
templates/distribution/manifests/monitoring/resources/ingress-infra.yml.tpl
templates/distribution/manifests/opa/resources/ingress-infra.yml.tpl
templates/distribution/scripts/apply.sh.tpl
templates/distribution/scripts/delete.sh.tpl

feat: add yq dependency and apply script template

---

Furyfile.yml
docs/releases/v1.25.3.md
docs/upgrades/v1.25.2-to-v1.25.3.md
releases/v1.25.3/Furyfile.yml
releases/v1.25.3/kfd.yaml
releases/v1.25.3/kustomization.yaml

Some informations were missing on the docs.
After the merge, we need to update also the release notes on the github releases

Chores - add more infos on kfd 1.25.3

---

kfd.yaml
templates/distribution/manifests/logging/kustomization.yaml.tpl
templates/distribution/manifests/logging/patches/minio.yml.tpl
templates/distribution/scripts/apply.sh.tpl
templates/distribution/scripts/delete.sh.tpl

Fix: minio pvc, load restrictor on kustomize, bump eks installer

---

docs/COMPATIBILITY_MATRIX.md
docs/releases/v1.26.1.md
docs/upgrades/v1.26.0-to-v1.26.1.md
releases/v1.26.1/Furyfile.yml
releases/v1.26.1/kfd.yaml
releases/v1.26.1/kustomization.yaml
templates/distribution/manifests/ingress/kustomization.yaml.tpl

Hotfix/fix ssl template + release 1.26.1

---

templates/distribution/manifests/opa/patches/kyverno-whitelist-namespace.yml.tpl

https://github.com/sighupio/product-management/issues/316

fix additional excluded namespaces in kyverno

---

templates/config/ekscluster-kfd-v1alpha2.yaml.tpl
templates/config/kfddistribution-kfd-v1alpha2.yaml.tpl
templates/config/onpremises-kfd-v1alpha2.yaml.tpl

Fix example `furyctl.yaml` config file generated by furyctl

Fix example config

---

pkg/apis/ekscluster/v1alpha2/private/schema.go
pkg/apis/ekscluster/v1alpha2/public/schema.go
pkg/apis/kfddistribution/v1alpha2/public/schema.go
pkg/apis/onpremises/v1alpha2/public/schema.go
schemas/public/onpremises-kfd-v1alpha2.json

feat: prevent the creation of clusters with 0 worker nodes

---

README.md

Update link to CNCF landscape

---

README.md
ROADMAP.md

- add recommended hardware requirements to the Architecture section in the readme for a standard production-grade installation.
- add roadmap file.

docs: add recommended requirements, roadmap

---

templates/distribution/scripts/pre-apply.sh.tpl

partially fixes: https://github.com/sighupio/furyctl/issues/487

fix: recucer not working switching from none to mimir with externalEndpoint

---

kfd.yaml
pkg/apis/ekscluster/v1alpha2/private/schema.go
pkg/apis/ekscluster/v1alpha2/public/schema.go
pkg/apis/kfddistribution/v1alpha2/public/schema.go
pkg/apis/onpremises/v1alpha2/public/schema.go
schemas/private/ekscluster-kfd-v1alpha2.json
schemas/private/ekscluster-kfd-v1alpha2.patch.json
schemas/public/ekscluster-kfd-v1alpha2.json
schemas/public/kfddistribution-kfd-v1alpha2.json
schemas/public/onpremises-kfd-v1alpha2.json
templates/distribution/terraform/cluster-autoscaler.tf.tpl
templates/distribution/terraform/ebs-csi-driver.tf.tpl
templates/distribution/terraform/load-balancer-controller.tf.tpl
templates/infrastructure/ekscluster/terraform/main.auto.tfvars.tpl
templates/infrastructure/ekscluster/terraform/main.tf.tpl
templates/infrastructure/ekscluster/terraform/variables.tf
templates/kubernetes/ekscluster/terraform/main.auto.tfvars.tpl
templates/kubernetes/ekscluster/terraform/main.tf.tpl
templates/kubernetes/ekscluster/terraform/variables.tf

to be tested with furyctl from branch [feature/increase-cluster-name-len](https://github.com/sighupio/furyctl/tree/feature/increase-cluster-name-len)

feat: increase cluster name length

---

pkg/apis/onpremises/v1alpha2/public/schema.go
schemas/public/onpremises-kfd-v1alpha2.json
templates/kubernetes/onpremises/ansible.cfg.tpl
templates/preflight/onpremises/ansible.cfg.tpl

Example:
```yaml
apiVersion: kfd.sighup.io/v1alpha2
kind: OnPremises
spec:
kubernetes:
advancedAnsible:
config: |
some = config
```

Add config field to advanced ansible

---

.drone.yml
templates/distribution/manifests/monitoring/kustomization.yaml.tpl
templates/distribution/manifests/monitoring/resources/haproxy-scrapeConfig.yaml.tpl
templates/distribution/scripts/pre-apply.sh.tpl

as per title, fixing templates when using KFDDistribution provider

fix: add guards on kfddistribution provider for haproxy scrape configs

---

docs/schemas/ekscluster-kfd-v1alpha2.md
docs/schemas/kfddistribution-kfd-v1alpha2.md
docs/schemas/onpremises-kfd-v1alpha2.md
pkg/apis/ekscluster/v1alpha2/private/schema.go
pkg/apis/ekscluster/v1alpha2/public/schema.go
pkg/apis/kfddistribution/v1alpha2/public/schema.go
pkg/apis/onpremises/v1alpha2/public/schema.go
schemas/public/spec-distribution-modules-auth-pomerium.json
templates/distribution/manifests/auth/resources/pomerium-policy.yml.tpl

Add pomerium policy settings for hubble ui

---

docs/schemas/ekscluster-kfd-v1alpha2.md
docs/schemas/kfddistribution-kfd-v1alpha2.md
docs/schemas/onpremises-kfd-v1alpha2.md
pkg/apis/ekscluster/v1alpha2/private/schema.go
pkg/apis/ekscluster/v1alpha2/public/schema.go
pkg/apis/kfddistribution/v1alpha2/public/schema.go
pkg/apis/onpremises/v1alpha2/public/schema.go
schemas/private/ekscluster-kfd-v1alpha2.json
schemas/public/ekscluster-kfd-v1alpha2.json
schemas/public/kfddistribution-kfd-v1alpha2.json
schemas/public/onpremises-kfd-v1alpha2.json

- Add missing description for the fields introduced in PR #213
- Regenerate markdown docs
- Regenerate go models

docs(schemas): add description for grafana's advanced configuration

---

.rules/.markdown-lint.yml
MAINTENANCE.md

Proposal for a first version of the maintenance guide for releasing a new version of KFD.

docs: add maintenance guide

---

.drone.yml
MAINTENANCE.md
README.md
docs/COMPATIBILITY_MATRIX.md
docs/releases/v1.27.9.md
docs/releases/v1.28.4.md
docs/releases/v1.29.4.md
kfd.yaml
templates/kubernetes/onpremises/98.cluster-certificates-renewal.yaml.tpl
tests/e2e-kfddistribution-upgrades.sh
tests/e2e/kfddistribution-upgrades/furyctl-init-cluster-1.29.3.yaml
tests/e2e/kfddistribution-upgrades/furyctl-init-cluster-1.29.4.yaml

feat: prepare v1.29.4 release

---

templates/kubernetes/onpremises/hosts.yaml.tpl

- Added `.spec.kubernetes.advanced` field check

fix: custom registry onpremises configuration

---

templates/kubernetes/onpremises/hosts.yaml.tpl

Cherry pick of https://github.com/sighupio/fury-distribution/pull/271.

fix: custom registry onpremises configuration on v1.28

---

templates/kubernetes/onpremises/hosts.yaml.tpl

Cherry pick of https://github.com/sighupio/fury-distribution/pull/271.

fix: custom registry onpremises configuration on v1.27

---

templates/distribution/scripts/pre-apply.sh.tpl

Fix auth migrations:
- Consider Hubble Ingress
- basicAuth -> sso was defined twice, so it was not working properly and sso->basicAuth was not working at all.

fix(templates/scripts): auth migrations

---

templates/distribution/manifests/dr/kustomization.yaml.tpl
templates/distribution/manifests/dr/patches/velero-schedule-full.yml.tpl
templates/distribution/manifests/dr/patches/velero-schedule-manifests.yml.tpl

fix: add checks to DR cron templates

---

docs/schemas/ekscluster-kfd-v1alpha2.md
pkg/apis/ekscluster/v1alpha2/private/schema.go
pkg/apis/ekscluster/v1alpha2/public/schema.go
schemas/private/ekscluster-kfd-v1alpha2.json
schemas/public/ekscluster-kfd-v1alpha2.json

fix: correct dns validation when nginx is single, dual or none

---

kfd.yaml

Update `kfd.yaml` to point to OPA `v1.13.0`. No other changes are necessary

feat(policy): update to opa v1.13.0

---

.drone.yml
docs/COMPATIBILITY_MATRIX.md
docs/releases/v1.29.5.md
tests/e2e-kfddistribution-upgrades.sh

This release follows closely what we already did for the v1.30.0 version.

Feat/release v1.29.5

---

.drone.yml
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

- Add tempaltes for issues, with 2 categories: Bugs and Feature Requests
- Add template for PRs with our agreed structure

feat: add Issues and PR templates

---

.drone.yml
README.md
docs/COMPATIBILITY_MATRIX.md
docs/releases/v1.27.9.md
docs/releases/v1.28.0.md
docs/releases/v1.28.1.md
docs/releases/v1.28.2.md
docs/releases/v1.28.3.md
docs/releases/v1.28.4.md
docs/releases/v1.28.5.md
docs/releases/v1.28.6.md
docs/releases/v1.29.0.md
docs/releases/v1.29.1.md
docs/releases/v1.29.2.md
docs/releases/v1.29.3.md
docs/releases/v1.29.4.md
docs/releases/v1.29.5.md
docs/releases/v1.29.6.md
docs/releases/v1.30.0.md
docs/releases/v1.30.1.md
docs/releases/v1.31.0.md

This PR depends on #330 #331 #332 , and adds all the docs and releases written on backported releases.
Also, updates the `.drone.yml` bumping furyctl version and re-enabling dependency between pipelines

feat: add all docs from backported releases

---

.drone.yml
tests/e2e/ekscluster-upgrades/e2e-ekscluster-upgrades.sh
tests/e2e/ekscluster-upgrades/furyctl_upgrade.expect
tests/e2e/ekscluster-upgrades/manifests/furyctl-init-cluster-1.30.1.yaml
tests/e2e/ekscluster-upgrades/manifests/furyctl-init-cluster-1.31.1.yaml
tests/e2e/ekscluster/e2e-ekscluster.sh
tests/e2e/ekscluster/furyctl_apply.expect
tests/e2e/ekscluster/furyctl_delete.expect
tests/e2e/ekscluster/furyctl_delete_force.expect
tests/e2e/ekscluster/manifests/furyctl-10-migrate-from-kyverno-default-policies-to-disabled.yaml
tests/e2e/ekscluster/manifests/furyctl-11-migrate-from-alertmanagerconfigs-to-disabled.yaml
tests/e2e/ekscluster/manifests/furyctl-2-migrate-from-tempo-to-none.yaml
tests/e2e/ekscluster/manifests/furyctl-3-migrate-from-kyverno-to-none.yaml
tests/e2e/ekscluster/manifests/furyctl-4-migrate-from-velero-to-none.yaml
tests/e2e/ekscluster/manifests/furyctl-5-migrate-from-loki-to-none.yaml
tests/e2e/ekscluster/manifests/furyctl-6-migrate-from-mimir-to-none.yaml
tests/e2e/ekscluster/manifests/furyctl-7-migrate-from-basicAuth-to-sso.yaml
tests/e2e/ekscluster/manifests/furyctl-8-migrate-from-sso-to-none.yaml
tests/e2e/ekscluster/manifests/furyctl-9-migrate-from-none-to-safe-values.yaml
tests/e2e/ekscluster/manifests/furyctl-cleanup-all.yaml
tests/e2e/ekscluster/manifests/furyctl-init-cluster.yaml

Improve and fix EKS e2e tests, work not yet completed
Closes:
Relates:

Feat/fix e2e release v1.31.1

---

tests/e2e/kfddistribution/furyctl-cleanup-all.yaml

tests: fix cleanup furyctl with correct distributionversion

---

tests/e2e/kfddistribution-upgrades/furyctl-init-cluster-1.30.1.yaml

fix: furyctl-init-cluster-1.30.1

---

.drone.yml

tests: use furyctl v0.32.0

---

.drone.yml

fix: e2e images

---

docs/releases/unreleased.md

Add a note about the immutability fix on control planes on `unreleased.md`.
Relates: https://github.com/sighupio/product-management/issues/651
Add a note on the release note about the fix made to the distribution in order to have the control plane immutability working again.
Nothing.
Nothing.
Nothing.

Add fix about immutability on `unreleased.md`

---

README.md
docs/releases/v1.33.0.md
kfd.yaml

feat: bump ingress version to v4.1.1
